use geeko;
insert into comentarios_reportados (idComentarioReportado, idReporte) values (2, 18);
insert into comentarios_reportados (idComentarioReportado, idReporte) values (10, 20);
insert into comentarios_reportados (idComentarioReportado, idReporte) values (1, 5);
insert into comentarios_reportados (idComentarioReportado, idReporte) values (14, 2);
insert into comentarios_reportados (idComentarioReportado, idReporte) values (23, 8);
insert into comentarios_reportados (idComentarioReportado, idReporte) values (13, 1);
insert into comentarios_reportados (idComentarioReportado, idReporte) values (9, 15);
insert into comentarios_reportados (idComentarioReportado, idReporte) values (24, 7);
insert into comentarios_reportados (idComentarioReportado, idReporte) values (15, 2);
insert into comentarios_reportados (idComentarioReportado, idReporte) values (11, 17);
