use geeko;
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (1, 18, 48, 'snielson0', 'http://dummyimage.com/206x100.png/dddddd/000000', 'primis in faucibus', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (2, 64, 88, 'ljolly1', 'http://dummyimage.com/209x100.png/dddddd/000000', 'nulla facilisi', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (3, 21, 60, 'eboxill2', 'http://dummyimage.com/239x100.png/cc0000/ffffff', 'erat eros viverra', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (4, 16, 45, 'gbarbie3', 'http://dummyimage.com/245x100.png/ff4444/ffffff', 'sociis natoque', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (5, 42, 43, 'statton4', 'http://dummyimage.com/220x100.png/5fa2dd/ffffff', 'risus dapibus', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (6, 50, 89, 'smaclucais5', 'http://dummyimage.com/163x100.png/ff4444/ffffff', 'orci pede venenatis', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (7, 49, 7, 'mfoggo6', 'http://dummyimage.com/134x100.png/cc0000/ffffff', 'ligula nec', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (8, 93, 11, 'bliver7', 'http://dummyimage.com/146x100.png/5fa2dd/ffffff', 'tortor', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (9, 58, 60, 'lmckew8', 'http://dummyimage.com/186x100.png/ff4444/ffffff', 'non sodales', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (10, 43, 7, 'dbradfield9', 'http://dummyimage.com/223x100.png/ff4444/ffffff', 'ut', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (11, 7, 60, 'fwinckwortha', 'http://dummyimage.com/138x100.png/ff4444/ffffff', 'nisi volutpat', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (12, 93, 32, 'emclartyb', 'http://dummyimage.com/174x100.png/ff4444/ffffff', 'eu mi nulla', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (13, 45, 13, 'jorumc', 'http://dummyimage.com/210x100.png/cc0000/ffffff', 'cum sociis', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (14, 6, 83, 'arylanced', 'http://dummyimage.com/216x100.png/ff4444/ffffff', 'elementum eu', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (15, 1, 50, 'mdorbere', 'http://dummyimage.com/236x100.png/5fa2dd/ffffff', 'eu', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (16, 44, 29, 'gferrarottif', 'http://dummyimage.com/121x100.png/5fa2dd/ffffff', 'commodo vulputate', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (17, 60, 78, 'gmadrellg', 'http://dummyimage.com/109x100.png/ff4444/ffffff', 'mauris morbi', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (18, 14, 53, 'mgioanh', 'http://dummyimage.com/159x100.png/cc0000/ffffff', 'nulla', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (19, 72, 47, 'bfairhursti', 'http://dummyimage.com/221x100.png/dddddd/000000', 'ipsum primis', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (20, 41, 64, 'jkendlej', 'http://dummyimage.com/215x100.png/ff4444/ffffff', 'volutpat erat', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (21, 66, 86, 'otorrk', 'http://dummyimage.com/170x100.png/ff4444/ffffff', 'volutpat in', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (22, 28, 52, 'kkiebesl', 'http://dummyimage.com/191x100.png/ff4444/ffffff', 'sed', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (23, 31, 52, 'ajaukovicm', 'http://dummyimage.com/232x100.png/5fa2dd/ffffff', 'tincidunt eget tempus', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (24, 71, 62, 'bbueyn', 'http://dummyimage.com/169x100.png/5fa2dd/ffffff', 'cras mi', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (25, 4, 59, 'scaffo', 'http://dummyimage.com/170x100.png/5fa2dd/ffffff', 'lacinia erat vestibulum', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (26, 87, 3, 'cmytonp', 'http://dummyimage.com/202x100.png/ff4444/ffffff', 'rhoncus', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (27, 34, 33, 'mhedgemanq', 'http://dummyimage.com/127x100.png/dddddd/000000', 'quam a', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (28, 41, 71, 'rizodr', 'http://dummyimage.com/114x100.png/5fa2dd/ffffff', 'primis in', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (29, 1, 14, 'dpowries', 'http://dummyimage.com/157x100.png/dddddd/000000', 'id', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (30, 77, 48, 'beamt', 'http://dummyimage.com/121x100.png/cc0000/ffffff', 'nibh', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (31, 11, 91, 'dnieceu', 'http://dummyimage.com/176x100.png/ff4444/ffffff', 'quam', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (32, 44, 32, 'jmctrustyv', 'http://dummyimage.com/203x100.png/5fa2dd/ffffff', 'vestibulum aliquet ultrices', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (33, 87, 18, 'glowthianw', 'http://dummyimage.com/174x100.png/cc0000/ffffff', 'vel est donec', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (34, 10, 49, 'sshanksx', 'http://dummyimage.com/177x100.png/ff4444/ffffff', 'lectus aliquam sit', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (35, 60, 5, 'gpriney', 'http://dummyimage.com/139x100.png/ff4444/ffffff', 'pulvinar', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (36, 11, 41, 'dcecerez', 'http://dummyimage.com/226x100.png/dddddd/000000', 'sapien quis', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (37, 53, 13, 'athomason10', 'http://dummyimage.com/173x100.png/cc0000/ffffff', 'non interdum in', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (38, 23, 95, 'kshaw11', 'http://dummyimage.com/162x100.png/cc0000/ffffff', 'et magnis dis', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (39, 78, 31, 'dyven12', 'http://dummyimage.com/150x100.png/5fa2dd/ffffff', 'ut erat curabitur', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (40, 78, 31, 'hpeidro13', 'http://dummyimage.com/206x100.png/cc0000/ffffff', 'eleifend donec', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (41, 62, 41, 'wpavel14', 'http://dummyimage.com/240x100.png/5fa2dd/ffffff', 'proin leo odio', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (42, 89, 24, 'apaff15', 'http://dummyimage.com/205x100.png/ff4444/ffffff', 'cubilia curae', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (43, 24, 62, 'nbrydson16', 'http://dummyimage.com/130x100.png/cc0000/ffffff', 'est', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (44, 74, 70, 'jprobetts17', 'http://dummyimage.com/161x100.png/dddddd/000000', 'ridiculus mus vivamus', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (45, 75, 22, 'tbrinklow18', 'http://dummyimage.com/166x100.png/cc0000/ffffff', 'ligula', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (46, 39, 92, 'ndeverale19', 'http://dummyimage.com/151x100.png/cc0000/ffffff', 'augue', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (47, 18, 64, 'ckingstne1a', 'http://dummyimage.com/119x100.png/dddddd/000000', 'cras', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (48, 33, 28, 'mtonnesen1b', 'http://dummyimage.com/227x100.png/5fa2dd/ffffff', 'suspendisse', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (49, 74, 31, 'ufulkes1c', 'http://dummyimage.com/237x100.png/cc0000/ffffff', 'vel dapibus', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (50, 100, 12, 'asuccamore1d', 'http://dummyimage.com/129x100.png/5fa2dd/ffffff', 'consectetuer eget rutrum', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (51, 95, 20, 'gjouhan1e', 'http://dummyimage.com/233x100.png/5fa2dd/ffffff', 'dignissim', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (52, 95, 31, 'ewankel1f', 'http://dummyimage.com/108x100.png/dddddd/000000', 'scelerisque mauris', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (53, 91, 73, 'dsisnett1g', 'http://dummyimage.com/144x100.png/dddddd/000000', 'magna ac consequat', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (54, 4, 61, 'mbenoix1h', 'http://dummyimage.com/242x100.png/5fa2dd/ffffff', 'faucibus cursus', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (55, 47, 9, 'rdudderidge1i', 'http://dummyimage.com/112x100.png/5fa2dd/ffffff', 'tincidunt', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (56, 63, 69, 'dpavlovic1j', 'http://dummyimage.com/140x100.png/ff4444/ffffff', 'nullam molestie nibh', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (57, 74, 8, 'dlaffling1k', 'http://dummyimage.com/227x100.png/ff4444/ffffff', 'tortor', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (58, 57, 28, 'arebbeck1l', 'http://dummyimage.com/209x100.png/dddddd/000000', 'aliquam', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (59, 90, 40, 'ddelve1m', 'http://dummyimage.com/202x100.png/dddddd/000000', 'faucibus accumsan', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (60, 66, 30, 'mbartell1n', 'http://dummyimage.com/248x100.png/cc0000/ffffff', 'vivamus', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (61, 22, 74, 'edcosta1o', 'http://dummyimage.com/223x100.png/cc0000/ffffff', 'sapien quis libero', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (62, 57, 23, 'kbillo1p', 'http://dummyimage.com/237x100.png/ff4444/ffffff', 'nascetur ridiculus', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (63, 58, 63, 'frowett1q', 'http://dummyimage.com/203x100.png/5fa2dd/ffffff', 'praesent lectus vestibulum', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (64, 12, 14, 'bwoodhall1r', 'http://dummyimage.com/192x100.png/cc0000/ffffff', 'eleifend donec ut', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (65, 30, 44, 'mbenwell1s', 'http://dummyimage.com/186x100.png/dddddd/000000', 'tempus sit', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (66, 34, 58, 'csharples1t', 'http://dummyimage.com/137x100.png/dddddd/000000', 'leo odio', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (67, 89, 30, 'egilli1u', 'http://dummyimage.com/208x100.png/cc0000/ffffff', 'nisi at', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (68, 9, 2, 'tramsden1v', 'http://dummyimage.com/119x100.png/dddddd/000000', 'semper interdum mauris', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (69, 38, 94, 'mgildroy1w', 'http://dummyimage.com/178x100.png/5fa2dd/ffffff', 'quisque', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (70, 45, 21, 'lpethrick1x', 'http://dummyimage.com/244x100.png/dddddd/000000', 'non velit', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (71, 87, 30, 'edyment1y', 'http://dummyimage.com/123x100.png/5fa2dd/ffffff', 'aliquam', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (72, 74, 28, 'jfutty1z', 'http://dummyimage.com/234x100.png/ff4444/ffffff', 'odio', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (73, 18, 6, 'jminichi20', 'http://dummyimage.com/207x100.png/ff4444/ffffff', 'potenti nullam porttitor', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (74, 82, 99, 'hturton21', 'http://dummyimage.com/233x100.png/dddddd/000000', 'aliquet ultrices erat', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (75, 32, 79, 'rdinisco22', 'http://dummyimage.com/215x100.png/cc0000/ffffff', 'vel lectus in', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (76, 84, 70, 'dhaskett23', 'http://dummyimage.com/194x100.png/ff4444/ffffff', 'eros vestibulum ac', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (77, 53, 1, 'mwillgress24', 'http://dummyimage.com/109x100.png/5fa2dd/ffffff', 'scelerisque', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (78, 30, 36, 'rwitten25', 'http://dummyimage.com/133x100.png/dddddd/000000', 'ornare imperdiet', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (79, 45, 41, 'searey26', 'http://dummyimage.com/213x100.png/5fa2dd/ffffff', 'consectetuer', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (80, 50, 8, 'rerrichiello27', 'http://dummyimage.com/147x100.png/ff4444/ffffff', 'nullam', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (81, 36, 19, 'ceke28', 'http://dummyimage.com/227x100.png/5fa2dd/ffffff', 'viverra diam vitae', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (82, 64, 98, 'mnovichenko29', 'http://dummyimage.com/241x100.png/cc0000/ffffff', 'congue risus', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (83, 81, 79, 'lferonet2a', 'http://dummyimage.com/103x100.png/5fa2dd/ffffff', 'diam id ornare', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (84, 41, 45, 'tdanbrook2b', 'http://dummyimage.com/161x100.png/cc0000/ffffff', 'in blandit', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (85, 86, 37, 'dschollick2c', 'http://dummyimage.com/104x100.png/ff4444/ffffff', 'adipiscing elit proin', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (86, 46, 28, 'icafferty2d', 'http://dummyimage.com/250x100.png/5fa2dd/ffffff', 'orci pede', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (87, 78, 89, 'hnurny2e', 'http://dummyimage.com/129x100.png/ff4444/ffffff', 'et eros', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (88, 33, 2, 'eburchill2f', 'http://dummyimage.com/234x100.png/ff4444/ffffff', 'lectus aliquam', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (89, 3, 82, 'tnaldrett2g', 'http://dummyimage.com/206x100.png/dddddd/000000', 'orci luctus et', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (90, 27, 95, 'afontenot2h', 'http://dummyimage.com/154x100.png/5fa2dd/ffffff', 'dis', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (91, 9, 68, 'cfarnham2i', 'http://dummyimage.com/173x100.png/ff4444/ffffff', 'in faucibus orci', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (92, 63, 52, 'mglencros2j', 'http://dummyimage.com/107x100.png/ff4444/ffffff', 'amet sem', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (93, 28, 49, 'lspencook2k', 'http://dummyimage.com/216x100.png/dddddd/000000', 'sed sagittis nam', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (94, 82, 81, 'msayre2l', 'http://dummyimage.com/153x100.png/5fa2dd/ffffff', 'venenatis', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (95, 15, 16, 'glydiatt2m', 'http://dummyimage.com/129x100.png/cc0000/ffffff', 'in', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (96, 66, 29, 'mbatterton2n', 'http://dummyimage.com/217x100.png/ff4444/ffffff', 'magna', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (97, 83, 7, 'ewhate2o', 'http://dummyimage.com/208x100.png/cc0000/ffffff', 'volutpat dui maecenas', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (98, 16, 34, 'mcarley2p', 'http://dummyimage.com/198x100.png/dddddd/000000', 'pellentesque', 0);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (99, 21, 38, 'olargen2q', 'http://dummyimage.com/248x100.png/dddddd/000000', 'vitae nisl', 1);
insert into chats (id, idDestinatario, idRemitente, titulo, imagen, descripcion, activo) values (100, 95, 20, 'mmcgilvary2r', 'http://dummyimage.com/218x100.png/ff4444/ffffff', 'massa id', 1);
